POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Food for Foodies",
    "author": "Hipster McPretentious",
    "url": "https://hippret.com/foodie/",
    "likes": 0
}